Traceback (most recent call last):
  File "rpc_client.py", line 42, in <module>
    conf_file = sys.argv[2]
IndexError: list index out of range
